In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    ### s'(x) = s(1−s) 
    s = sigmoid(x)
    ds = s * (1 - s)
    return ds

In [17]:
def L1(yhat, y):
    """
    L1(y^,y)=∑i{0, m}|y(i)−y(i)^|
    """
    loss = np.sum(np.abs(yhat - y))
    return loss

In [19]:
def L2(yhat, y):
    """
    L2(y^,y)=∑i{0, m}(y(i)−y(i)^)^2
    """
    #loss = np.sum(np.abs(yhat - y)**2)
    loss = np.dot(y-yhat,y-yhat)
    return loss

In [21]:
def test():
    v1 = np.array([1,2,3])
    print(v1, np.shape(v1))
    
    v2 = sigmoid(v1)
    print(v2, np.shape(v2))
    
    v3 = sigmoid_derivative(v1)
    print(v3, np.shape(v3))
    
    vn = np.linalg.norm(v1, axis = 0, keepdims=True)
    print(vn, np.shape(vn)) 
    
    v4 = v1 / vn
    print(v4, np.shape(v4))
    
    v5 = np.outer(v1, v1)
    print(v5, np.shape(v5))    
    
    v6 = L1(v2, v3)
    print(v6, np.shape(v6))
    
    v7 = L2(v2, v3)
    print(v7, np.shape(v7))
test()

[1 2 3] (3,)
[0.73105858 0.88079708 0.95257413] (3,)
[0.19661193 0.10499359 0.04517666] (3,)
[3.74165739] (1,)
[0.26726124 0.53452248 0.80178373] (3,)
[[1 2 3]
 [2 4 6]
 [3 6 9]] (3, 3)
2.2176476050544203 ()
1.7108744391417539 ()
